version: '3'
services:
    ubuntu-pkg:
        build:
        context: .
        target: ubuntu-pkg
    ubuntu-bin:
        build:
        context: .
        target: ubuntu-bin
    ubuntu-src:
        build:
        context: .
        target: ubuntu-src
